#' A data.table containing methylation data 
#' (position, number methylated reads and number of reads total)
#' This object contains reduced
#' representation bisulfite sequencing data from the
#' GM06990 B-lymphoblastoid cell line that was generated by the ENCODE
#' project (GEO accession GSE27584, sample GSM980583). 
#' Only a subset of the full data is used in this object and the 
#' data was switched from hg19 to hg38.
#'
#'
#' @docType data
#' @keywords datasets
#' @name exampleBSDT
#' @usage data(exampleBSDT)
#' @format A data.table, data.frame object
NULL

#' A GRanges object with a ranges corresponding to Nrf1 Chip-seq peaks
#' in the GM12878 B-lymphoblastoid cell line (GEO accession GSE31477, 
#' sample GSM935309). Only a subset of the ranges are used in 
#' this object and the regions were switched from hg19 to hg38.
#'
#'
#' @docType data
#' @keywords datasets
#' @name exampleRegionSet
#' @usage data(exampleRegionSet)
#' @format A GRanges object
NULL

#' A data.table with annotation for a bisulfite sample (name and sample type) 
#'
#'
#' @docType data
#' @keywords datasets
#' @name exampleAnnoDT1
#' @usage data(exampleAnnoDT1)
#' @format A data.table, data.frame object
NULL

#' A data.table with artificial binned methylation data
#'
#'
#' @docType data
#' @keywords datasets
#' @name exampleBins
#' @usage data(exampleBins)
#' @format A data.table, data.frame object
NULL

#' A data.table with binned methylation data for the first part of
#' the "Applying MIRA to a Biological Question" vignette. 
#' Has data for 3 Ewing samples and 3 muscle-related 
#' samples (human skeletal myoblasts and other related
#' samples). It is the product of `aggregateMethyl`.
#'
#'
#' @docType data
#' @keywords datasets
#' @name bigBinDT1
#' @usage data(bigBinDT1)
#' @format A data.table, data.frame object
NULL

#' A data.table with binned methylation data for the second part
#' of the "Applying MIRA to a Biological Question" vignette. 
#' Has data for 12 Ewing samples and 12 muscle-related samples 
#' (human skeletal myoblasts and other related
#' samples). It is the product of `aggregateMethyl`.
#'
#'
#' @docType data
#' @keywords datasets
#' @name bigBinDT2
#' @usage data(bigBinDT2)
#' @format A data.table, data.frame object
NULL

#' A data.table with annotation data for the "Applying MIRA to a 
#' Biological Question" vignette. Has annotation data (sampleName
#' and sampleType columns) for 24 Ewing samples and 24 muscle-related
#' samples (human skeletal myoblasts and other related samples).
#'
#'
#' @docType data
#' @keywords datasets
#' @name exampleAnnoDT2
#' @usage data(exampleAnnoDT2)
#' @format A data.table, data.frame object
NULL
